"""LaunchForge AI: marketplace launch agent for Swarms creators.

This file is intentionally self-contained so marketplaces and reviewers can
inspect the main implementation without navigating a nested project structure.
"""

from __future__ import annotations

import json
from typing import Any, Literal

from swarms import Agent

ProductType = Literal["prompt", "agent", "tool"]


SYSTEM_PROMPT = """
You are LaunchForge AI, a marketplace launch strategist for AI creators.

Your mission:
Turn raw AI product ideas into marketplace-ready Swarms listings for prompts,
agents, and tools.

You help creators clarify:
- target buyer
- buyer pain
- marketplace category
- positioning
- listing name
- tagline
- description
- tags
- practical use cases
- demo prompts
- implementation notes
- payload drafts
- quality warnings

Core behavior:
1. If the idea is usable, generate the launch package directly.
2. Ask at most 3 clarifying questions only when the idea is too vague.
3. Be concrete and workflow-focused.
4. Avoid generic productivity claims.
5. Avoid unsupported income, legal, financial, or medical guarantees.
6. For regulated domains, use assistive language and include safety notes.
7. Output valid JSON only. Do not wrap the JSON in markdown.

Use one Swarms marketplace category:
Healthcare, Education, Finance, Research, Public Safety, Marketing, Sales,
Customer Support, Other.

Quality scoring:
- 90-100: clear buyer, concrete workflow, differentiated, publish-ready
- 75-89: publishable, but needs stronger examples or proof
- 50-74: useful idea, but too broad or under-specified
- below 50: not ready for launch

Return this exact JSON shape:
{
  "market_analysis": {
    "category": "",
    "target_buyer": "",
    "buyer_pain": "",
    "why_now": "",
    "competition_note": "",
    "positioning": ""
  },
  "listing": {
    "name": "",
    "tagline": "",
    "description": "",
    "tags": [],
    "use_cases": [
      {
        "title": "",
        "description": ""
      }
    ],
    "demo_prompts": [],
    "pricing_angle": "",
    "trust_and_safety_notes": []
  },
  "implementation_brief": {
    "product_type": "",
    "core_prompt_or_agent_behavior": "",
    "recommended_requirements": [],
    "integration_notes": [],
    "launch_checklist": []
  },
  "payload_draft": {
    "prompt_payload": null,
    "agent_payload": null,
    "tool_payload": null
  },
  "quality_score": {
    "score": 0,
    "strengths": [],
    "warnings": [],
    "next_improvements": []
  }
}
"""


def normalize_tags(tags: str | list[str]) -> str:
    """Normalize tags into a comma-separated string.

    Args:
        tags: A comma-separated tag string or list of tag strings.

    Returns:
        A deduplicated comma-separated tag string.
    """
    raw_tags = tags.split(",") if isinstance(tags, str) else tags
    cleaned: list[str] = []
    seen: set[str] = set()

    for tag in raw_tags:
        normalized = str(tag).strip().lstrip("#")
        if not normalized:
            continue
        key = normalized.lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(normalized)

    return ", ".join(cleaned)


def validate_listing_package(package: dict[str, Any]) -> dict[str, Any]:
    """Validate a LaunchForge listing package for marketplace readiness.

    Args:
        package: A listing package generated by LaunchForge AI.

    Returns:
        A validation report with errors, warnings, and a readiness boolean.
    """
    errors: list[str] = []
    warnings: list[str] = []

    listing = package.get("listing", {})
    market = package.get("market_analysis", {})

    if not listing.get("name"):
        errors.append("Missing listing.name")
    if len(str(listing.get("description", ""))) < 120:
        warnings.append("Description should be more specific and at least 120 characters.")
    if not market.get("target_buyer"):
        errors.append("Missing market_analysis.target_buyer")
    if not market.get("buyer_pain"):
        errors.append("Missing market_analysis.buyer_pain")

    use_cases = listing.get("use_cases", [])
    if not isinstance(use_cases, list) or len(use_cases) < 3:
        warnings.append("Add at least 3 practical use cases.")

    tags = listing.get("tags", [])
    if isinstance(tags, list) and len(tags) < 4:
        warnings.append("Add at least 4 searchable tags.")

    demo_prompts = listing.get("demo_prompts", [])
    if not isinstance(demo_prompts, list) or len(demo_prompts) < 2:
        warnings.append("Add at least 2 demo prompts.")

    return {
        "is_ready": not errors,
        "errors": errors,
        "warnings": warnings,
    }


def create_launchforge_agent(model_name: str = "gpt-4o-mini") -> Agent:
    """Create the LaunchForge AI Swarms agent.

    Args:
        model_name: LiteLLM-compatible model name.

    Returns:
        A configured Swarms Agent for marketplace listing generation.
    """
    return Agent(
        agent_name="LaunchForge-AI",
        agent_description=(
            "Marketplace launch strategist that turns raw AI ideas into "
            "Swarms-ready listings, payload drafts, and quality checks."
        ),
        system_prompt=SYSTEM_PROMPT,
        model_name=model_name,
        max_loops=1,
        output_type="json",
        tools=[validate_listing_package, normalize_tags],
    )


def run_launchforge(
    idea: str,
    product_type: ProductType = "prompt",
    target_buyer: str = "",
    category: str = "",
    technical_details: str = "",
    pricing_goal: str = "",
    model_name: str = "gpt-4o-mini",
) -> str:
    """Generate a marketplace-ready launch package.

    Args:
        idea: Raw AI product idea.
        product_type: Product type: prompt, agent, or tool.
        target_buyer: Optional target buyer segment.
        category: Optional preferred marketplace category.
        technical_details: Optional APIs, packages, data sources, or code notes.
        pricing_goal: Optional pricing or monetization goal.
        model_name: LiteLLM-compatible model name.

    Returns:
        A JSON string with a complete launch package.
    """
    task = {
        "idea": idea,
        "product_type": product_type,
        "target_buyer": target_buyer,
        "category": category,
        "technical_details": technical_details,
        "pricing_goal": pricing_goal,
    }

    agent = create_launchforge_agent(model_name=model_name)
    return agent.run(json.dumps(task, ensure_ascii=False))


if __name__ == "__main__":
    print(
        run_launchforge(
            idea=(
                "A creator tool that turns rough AI product ideas into "
                "Swarms marketplace listings and payload drafts."
            ),
            product_type="agent",
            target_buyer="Swarms creators and AI product builders",
            category="Other",
            technical_details="Uses structured JSON output and listing validation tools.",
            pricing_goal="Launch free first, then offer a paid pro workflow.",
        )
    )
